/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banksystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Dashboard extends javax.swing.JFrame {
    
    private Account userAccount;    //Initialization for the currentAccount, which came from line 192 of GUI.java.
    private double amount;          //initialization of amount.
    private Database db;   
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard( Account account, Database thisDB ) { 
        
        this.userAccount = account;
        this.db = thisDB;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tagiya1 = new javax.swing.JLabel();
        logoutbut1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 120), new java.awt.Dimension(20, 120), new java.awt.Dimension(20, 120));
        deplabel2 = new javax.swing.JTextField();
        depbut2 = new javax.swing.JButton();
        withdrawlabel2 = new javax.swing.JTextField();
        withdrawbut2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard of: " + userAccount.getUsername() + ".");
        setResizable(false);

        tagiya1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        tagiya1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tagiya1.setText("Balance: P " + userAccount.getBalance() );

        logoutbut1.setText("Logout");
        logoutbut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbut1ActionPerformed(evt);
            }
        });

        deplabel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deplabel2ActionPerformed(evt);
            }
        });

        depbut2.setText("Deposit");
        depbut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depbut2ActionPerformed(evt);
            }
        });

        withdrawlabel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawlabel2ActionPerformed(evt);
            }
        });

        withdrawbut2.setText("Withdraw");
        withdrawbut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawbut2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tagiya1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(logoutbut1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withdrawlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deplabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(depbut2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withdrawbut2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tagiya1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutbut1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deplabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depbut2))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(withdrawlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(withdrawbut2))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbut1ActionPerformed
    javax.swing.JOptionPane.showMessageDialog(this, "You have been logged out!", "Successful", JOptionPane.PLAIN_MESSAGE);
    GUI gui = new GUI();
    gui.setVisible(true);
    this.dispose();     //This part logs out the current user and creates a new instance of our GUI.
    }//GEN-LAST:event_logoutbut1ActionPerformed

    private void depbut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depbut2ActionPerformed
    
    amount = Double.parseDouble(deplabel2.getText());   //COnverts string to double, since userAccount.deposit is double.
    
        userAccount.deposit(amount);
        db.saveAll();                                   //Saves the new balance into the database.
        tagiya1.setText( "Balance: P " + userAccount.getBalance() );
        javax.swing.JOptionPane.showMessageDialog(this, "Deposit successful", "Successful", JOptionPane.PLAIN_MESSAGE);
   
        deplabel2.setText("");                          //For practicality.
        
    }//GEN-LAST:event_depbut2ActionPerformed

    private void withdrawbut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawbut2ActionPerformed
    
        amount = Double.parseDouble(withdrawlabel2.getText());    
        
            if ( userAccount.withdraw(amount) == true) {
            
            db.saveAll();
            tagiya1.setText( "Balance: P " + userAccount.getBalance() );
            javax.swing.JOptionPane.showMessageDialog(this, "Withdrawal successful!", "Successful", JOptionPane.PLAIN_MESSAGE);
            
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Withdrawal unsuccessful.", "Unsuccessful", JOptionPane.ERROR_MESSAGE);
            }
            
        withdrawlabel2.setText("");
        
    }//GEN-LAST:event_withdrawbut2ActionPerformed

    private void deplabel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deplabel2ActionPerformed
    depbut2.doClick();        
    }//GEN-LAST:event_deplabel2ActionPerformed

    private void withdrawlabel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawlabel2ActionPerformed
    withdrawbut2.doClick();        
    }//GEN-LAST:event_withdrawlabel2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton depbut2;
    private javax.swing.JTextField deplabel2;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton logoutbut1;
    private javax.swing.JLabel tagiya1;
    private javax.swing.JButton withdrawbut2;
    private javax.swing.JTextField withdrawlabel2;
    // End of variables declaration//GEN-END:variables
}